### ISSUE TITLE
功能建議：日期篩選和塗墨點數

### ISSUE THREAD

**Issue by aaaaa6505** [zhxie/conch-bay#12]
您好，非常感謝您開發「法螺灣」APP，讓iOS用戶有完整的數據統計系統。

在功能和介面上，提供兩個許願建議，
1.篩選功能：可以依據日期來篩選比賽區間，例如「當日」、「７天」、「當月份」，提供玩家比較不同區間的數據
2.「統計」：紀錄統計可加上「塗墨點數」的加總和每場平均

以上簡短建議，謝謝您!

**Comment by zhxie** [comment]
你好，感谢你的使用反馈。

1. 法螺湾自1.4.0起增加了筛选时间段的功能，请在主页面长按“載入更多”以加载指定时间段内的记录。此外，这一功能尚未完善，目前仅能加载“～当前”的记录，之后我们会补充自由选择时间范围的能力。
2. Oops，这是一个疏忽，我们会在下个版本更新时补充。
