### ISSUE TITLE
报错：unexpected fest match mode open

### ISSUE THREAD

**Issue by lychichem** [zhxie/conch-bay#28]
![Screenshot_2023-09-08-11-33-35-30_5aca8ebc0dd933b4663987e8de860b27.jpg](https://github.com/zhxie/conch-bay/assets/9316590/afd7d68f-811f-4373-a7f5-d5e6c92654ee)

尝试启动时即出现此错误

**Comment by zhxie** [comment]
It has been fixed in https://github.com/zhxie/conch-bay/commit/d2e5a8cd54effa177a5299b8ecb6f97f8b0a56df, please check the CI build.
