### ISSUE TITLE
转换ikax3时有数值发生改变

### ISSUE THREAD

**Issue by PangPang-O** [zhxie/conch-bay#32]
感谢作者大大的APP和脚本！

我在导入导出数据时发现了一些问题：

- 使用convert_ikax3.py将ikax3转换为conch-bay-import.json时，一部分祭典对战的贡献度（["data"]["vsHistoryDetail"]["festMatch"]["contribution"]）数值发生了改变。比如一场100倍的，原本的贡献度为“221872”，转换后则变成了“4597153792”。  
    - 我从我的祭典对战记录里筛选数据对比了下，原本贡献度小于等于2036的转换后数值没变，原本2050转换后变成了2560，原本2054变成了3584，原本2057变成了4352。贡献度大于等于2050的几乎都发生了变化（唯一一条例外的是贡献度为2304的一局，转换前后没改变）  
    - 只出现在用convert_ikax3.py脚本转换的情况，如果用法螺湾app直接导入ikax3的话则该条数据都是正常的。
- 在app里导入ikax3后，其中的打工记录没有大招数据，查看数据，发现大招id（ ["specialWeapon"]["weaponId"]）数值发生了改变。 
    - Booyah Bomb、Wave Breaker、Killer Wail 5.1、Inkjet、Crab Tank、Reefslider导入后的id分别变成了：29696、29952、30464、30720、31232、31488，正确应为20006、20007…20013
- 此外，导入salmdroidnw数据及用convert_salmdroidnw_backup.py转换时，只能转换1000条记录。应该是因为salmdroidnw将每1000条记录保存为一个文件（我在salmdroidnw里有2200+条记录，备份的压缩包里有summary、0、1、2、3，一共5个文件），而脚本只读了1号文件。

**Comment by zhxie** [comment]
- [ ] Unexpected Splatfest cloud change when convert IKAX3 using `tools/convert_ikax3.py`
- [ ] Missing special weapon (due to incorrect weapon ID) in Salmon Run when import IKAX3
- [ ] Only import the first file of salmdroidNW backup

对于第1个问题，能否提供一下IKAX3以及对应的对战ID或时间等信息方便问题定位呢？

**Comment by PangPang-O** [comment]
感谢回复！我该怎么发送文件过去呢？

**Comment by zhxie** [comment]
> 感谢回复！我该怎么发送文件过去呢？

你可以通过App中的支持发送邮件，或直接发送邮件到conch-bay@outlook.com。

另，关于第1与第2个问题，我本地验证并没有问题，所以提供IKAX3时最好能附上对战/打工 ID或时间等信息。

**Comment by PangPang-O** [comment]
已发邮件！

第2个问题后来发现我写得不对，纠正一下：跟第1个问题一样只出现在用convert_ikax3.py脚本转换的情况，从app直接导入ikax3则数据正常。
（但是weaponId正确的情况下还是没有打工大招的图标，所以可能是资源加载的问题？）

还有一个问题，如果用app导入convert_ikax3.py转换后的conch-bay-import.json文件，可以把所有的记录都导入进去。但用app直接导入ikax3，则打工记录只能导入400+条，最早的一条记录为2023.02.19的。

我运行脚本的Python版本为：Python 3.12.1（Win 10）
法螺湾app的版本应该是：Google Play Store的2023年12月4日的2.0.0版本

**Comment by zhxie** [comment]
- [ ] Only import 400 job results of IKAX3

> 第2个问题后来发现我写得不对，纠正一下：跟第1个问题一样只出现在用convert_ikax3.py脚本转换的情况，从app直接导入ikax3则数据正常。 （但是weaponId正确的情况下还是没有打工大招的图标，所以可能是资源加载的问题？）

出于资源版权的考虑（相比起API使用更加敏感），法螺湾不包含任何素材资源，仅使用记录中的资源链接缓存素材资源。ikawidget3备份中包含完整的资源链接，但有效期仅为1年，salmdroidNW备份不包含完整的资源链接。也就是说，实际上导入ikawidget3或salmdroidNW备份都无法加载素材资源。但如果通过法螺湾加载新记录的话，法螺湾会从这些新记录的资源链接中缓存素材资源，而这些缺失的素材资源也将得到补充。

> 我运行脚本的Python版本为：Python 3.12.1（Win 10） 法螺湾app的版本应该是：Google Play Store的2023年12月4日的2.0.0版本

由于诸多原因，Google Play上的法螺湾已经停止维护了，请考虑使用CI构建的版本 https://github.com/zhxie/conch-bay/actions/runs/8284296507

**Comment by PangPang-O** [comment]
> 所有问题均已验证并得到修复，请确认CI构建 https://github.com/zhxie/conch-bay/actions/runs/8596802812

感谢！辛苦了！

> 出于资源版权的考虑（相比起API使用更加敏感），法螺湾不包含任何素材资源，仅使用记录中的资源链接缓存素材资源。ikawidget3备份中包含完整的资源链接，但有效期仅为1年，salmdroidNW备份不包含完整的资源链接。也就是说，实际上导入ikawidget3或salmdroidNW备份都无法加载素材资源。但如果通过法螺湾加载新记录的话，法螺湾会从这些新记录的资源链接中缓存素材资源，而这些缺失的素材资源也将得到补充。

原来是这样啊，谢谢告知。

已确认问题1、2、3均已修复，转换后数值无误且salmdroidnw备份可以全部转换。
但是安装新版本app后无法正常导入。

- app导入conch-bay-import.json时（导入ikax3的情况也类似），屏幕上方显示“已加载xx项记录”后，又等待了数十分钟，屏幕仍然显示“加载更多中”，无法显示游戏记录（此时统计、趋势、场次等已经可以点开并正常显示）。关闭app，再次打开，报错：
    > database corrupted: Call to function
    > 'NativeStatement.finalizeAsync' has been rejected.
    > → Caused by: Error code
    > : disk I/O error
    
    再次关闭后打开，仍然报同样的错误
- app导入salmdroidnw的备份文件，屏幕上方报错：
    > JSON Parse error: Unexpected character:P 

    （PC上用convert_salmdroidnw_backup.py可以正常转换）

**Comment by zhxie** [comment]
> * app导入conch-bay-import.json时（导入ikax3的情况也类似），屏幕上方显示“已加载xx项记录”后，又等待了数十分钟，屏幕仍然显示“加载更多中”，无法显示游戏记录（此时统计、趋势、场次等已经可以点开并正常显示）。关闭app，再次打开，报错：
>   > database corrupted: Call to function
>   > 'NativeStatement.finalizeAsync' has been rejected.
>   > → Caused by: Error code
>   > : disk I/O error

由于鱿鱼圈3的记录实在是太大了，如果一次性打开完整的数据可能会内存不足，因此建议在导入时选择“分割并导入”。我只有iOS设备，并对邮件中的IKAX3做了测试，4000余则记录大约能在10分钟左右导入完成。Android设备众多，究竟能请求到多少内存我也不清楚，法螺湾导入的策略非常保守，因此可能需要很长～的时间但总归能导入完成的。如果觉得自己的硬件（软件）撑得过来也可以在导入时选择“（直接）导入”。
报错的原因估计是数据库损坏了，可以考虑导出数据（如果有任何需要导出的）后，在支持中清除数据库重新导入。
或者有需要的话，我也可以将邮箱中的IKAX3转换成conch-bay-import.json后，再手动切成小份的数据发还给你一个一个导入。

> * app导入salmdroidnw的备份文件，屏幕上方报错：
>   > JSON Parse error: Unexpected character:P

这个我也没有遇到过，也可以将样本通过邮件发送给我，我本地尝试一下。

**Comment by PangPang-O** [comment]
> 由于鱿鱼圈3的记录实在是太大了，如果一次性打开完整的数据可能会内存不足，因此建议在导入时选择“分割并导入”。

应该不是记录太大的问题，我用了一个仅有100条记录的11MB的小json文件进行试验的，几秒内就可以处理完毕。
同样的json在老版本中可以正常导入，在屏幕上方提示“已加载xx项记录”后马上就出现了对战记录且可以查看。但是在新版本中，如之前的描述，提示已加载后，过了很久仍然显示“加载更多中”。
导入ikax3时，大概10分钟后提示“加载xxxx项记录中”，继续放置2小时后仍在导入界面无变化（老版本大概10-20分钟导入完成）。

> JSON Parse error: Unexpected character:P

这个后来发现是我点错了，点了导入json文件的“导入”按钮，然后选择了salmdroidnw的.zip文件😂。用“导入salmdroidNW备份”的按钮可以正常导入了。

导入salmdroidNW备份后，上方提示“2292项记录，3000项跳过”，2292项记录正确，3000项记录是不合理的。
然后导入的打工记录没有自动显示，重启app后才显示出来。
此时界面下方“统计、趋势、场次”3个按钮无法正常使用，点击则一直在转圈。

**Comment by zhxie** [comment]
> 导入salmdroidNW备份后，上方提示“2292项记录，3000项跳过”，2292项记录正确，3000项记录是不合理的。 

已修复。请使用最新的CI构建 https://github.com/zhxie/conch-bay/actions/runs/8612509011

> 应该不是记录太大的问题，我用了一个仅有100条记录的11MB的小json文件进行试验的，几秒内就可以处理完毕。 同样的json在老版本中可以正常导入，在屏幕上方提示“已加载xx项记录”后马上就出现了对战记录且可以查看。但是在新版本中，如之前的描述，提示已加载后，过了很久仍然显示“加载更多中”。 导入ikax3时，大概10分钟后提示“加载xxxx项记录中”，继续放置2小时后仍在导入界面无变化（老版本大概10-20分钟导入完成）。
 
> 然后导入的打工记录没有自动显示，重启app后才显示出来。 此时界面下方“统计、趋势、场次”3个按钮无法正常使用，点击则一直在转圈。

这些问题我无法在本地复现，请在更新到最新的构建后再次尝试。如果问题依然存在，考虑到数据库可能损坏，你可以将数据样本和数据库（在法螺湾的支持的最下方调试选项中导出数据库）一并通过邮件发送给我。

**Comment by PangPang-O** [comment]
安装了最新的构建后，已确认导入salmdroidnw备份的提示正确，导入的打工记录不会自动显示的问题也修复了。但是json导入后持续在加载中、导入salmdroidnw备份无法使用“统计、趋势、场次”功能的问题依旧。

我在另一台几乎没装东西的安卓设备里安装了最新的构建，同样的问题仍然存在。所以我想该问题应该不是局限于一台设备。

导入salmdroidnw备份后，除了那3个按钮无法使用之外，还发现按“显示更多”往前大约翻到第80条时，无法加载更多，该按钮变成了“加载更多中”

点击“导出”，上方冒出disk I/O error的提示：

> Call to function
> 'NativeStatement.finalizeAsync' has been rejected.
> → Caused by: Error code
> : disk I/O error

在“支持”中可以导出数据库。（通过json导入时与该情况相同，无法使用“导出”按钮，只能在支持页面导出数据库）

导出的数据库文件将通过邮件发送

**Comment by zhxie** [comment]
了解了，我会部署一下Android模拟器进行测试，怀疑是某个依赖的平台适配性问题。

**Comment by zhxie** [comment]
经过测试，小数据量的salmdroidNW备份、IKAX3以及记录JSON均可正常导入，大数据量的IKAX3以及记录JSON在Build 144及之前可正常导入，Build 145及之后或因内存不足崩溃。我会回归Build 145中对内存检测的更改。
你提到的其他问题均未能复现，可能只会在特定OS或机型下出现。如果需要，你可以重新提交一个issue，我会打上help wanted的标签。

**Comment by zhxie** [comment]
近期的更新加入了对备份的压缩与解压缩的支持，相关的tools以及app内的导入与导出都进行了修改，性能得到了极大的提升。如果你依然遇到导入与导出相关的问题，可以尝试https://github.com/zhxie/conch-bay/actions/runs/8802546224及之后的构建。

**Comment by PangPang-O** [comment]
> 近期的更新加入了对备份的压缩与解压缩的支持，相关的tools以及app内的导入与导出都进行了修改，性能得到了极大的提升。如果你依然遇到导入与导出相关的问题，可以尝试 https://github.com/zhxie/conch-bay/actions/runs/8802546224 及之后的构建。

感谢告知！

安装了最新的构建，仍然报错`'NativeStatement.finalizeAsync' has been rejected.`及`disk I/O error`。应该不是导入导出相关的问题，可能是导入完成后数据库访问或者async方面的问题。

另外，在最新构建（Build #258）下尝试导入.zip格式的对战记录，报错

> Cannot read property 'unzip' of undefined

点击“导出”按钮，报错

> Cannot read property 'zip' of undefined

**Comment by zhxie** [comment]
我个人怀疑是因为之前测试的时候你的2台设备法螺湾都中途退出了，所以留下了一些脏数据导致导入导出无法进行。不知道你那边有没有清除应用数据的能力，在干净的环境下再试。
